name: "CrazyEnvoys"

main: "${group}.CrazyEnvoys"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.19"
description: ${description}

softdepend:
  - CMI
  - HolographicDisplays
  - DecentHolograms
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - MultiWorld
  - WorldEdit
  - WorldGuard

commands:
  envoys:
    description: "Manage your envoys however you want."
    aliases:
      - envoy

permissions:
  crazyenvoys.admin:
    default: op